### ISSUE TITLE
Extremely sensitive mouse input

### ISSUE THREAD

**Issue by MajickTek** [PixelGuys/Cubyz#7]
I came across this repo looking for a minecraft clone that i could mess with that wasn’t too big like terasology.

Anyways I made a new eclipse workspace and imported all three of the projects into it. No errors.

 I then proceeded to build and run the client, only to find that the slightest movement of my mouse would cause the camera to violently spin around, making it impossible to do anything.

Any possible fix for this issue?

P.S. my OS is Windows 10 home.

**Comment by zenith391** [comment]
Might be due to Cubyz using some specific mouse state that's probably not supported on Windows 10. I'll change it and it will normally work for you

**Comment by zenith391** [comment]
Should be fixed now, alongside another bug

**Comment by MajickTek** [comment]
Thanks!

**Comment by MajickTek** [comment]
@zenith391 the bug is not fixed, i just redownloaded the repo and tried to run the game, same issue.

**Comment by zenith391** [comment]
Aight, is your mouse any different than normal mouses (different than 2 buttons, 1 mouse wheel), maybe with configurable DPI?

**Comment by MajickTek** [comment]
No it’s a standard mouse with a left/right click, a middle click on the scroll wheel, and 2 side buttons.

**Comment by zenith391** [comment]
The bug should now be fixed, i hope this works now.

**Comment by IntegratedQuantum** [comment]
Fixed in 4b6f7b2.

This fix has been confirmed by another tester.
